; Generated by AutoGUI 2.5.4
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Menu Tray, Icon, shell32.dll, 319

Gui Color, 0x474747
Gui Add, Button, gLine x32 y144 w150 h40, Line Creator
Gui Add, Button, gMon x32 y192 w150 h40, Auto Monday
Gui Add, Button, gTues x32 y240 w150 h40, Auto Tuesday
Gui Add, Button, gWed x32 y288 w150 h40, Auto Wednesday
Gui Add, Button, gThur x32 y336 w150 h40, Auto Thursday
Gui Add, Button, gFri x32 y384 w150 h40, Auto Friday
Gui Add, Button, gBatcher x32 y432 w150 h40, Auto Batcher
Gui Add, Picture, x16 y8 w199 h123, %A_ScriptDir%\images\kdi-logo.png
Gui Add, Text, x-24 y128 w736 h3 +0x10
Gui Add, StatusBar,, Status Bar
Gui Font, c0xFFFFFF
Gui Add, Text, x224 y8 w120 h23 +0x200, Author: Neal Hollaway
Gui Font
Gui Font, c0xFFFFFF
Gui Add, Text, x224 y24 w120 h23 +0x200, Ver: 1.2
Gui Font
Gui Font, s14 c0xFFFFFF
Gui Add, Text, x200 y144 w120 h23 +0x200, How to use:
Gui Font
Gui Font, c0xFFFFFF
Gui Add, Tab3, x200 y168 w489 h297, Creator|Auto Day|Batcher
Gui Font
Gui Tab, 1
Gui Font, s10 c0xFFFFFF
Gui Add, Text, x208 y264 w435 h23 +0x200, 1. Ensure that E21 is running with the window open
Gui Font
Gui Font, s10 c0xFFFFFF
Gui Add, Text, x208 y296 w435 h23 +0x200, 2. Navigate to Final Production Schedule
Gui Font
Gui Font, s10 c0xFFFFFF
Gui Add, Text, x208 y328 w435 h23 +0x200, 3. Click Line Creator Button and follow prompts
Gui Font
Gui Font, s10 c0xFFFFFF
Gui Add, Text, x208 y216 w434 h29 +0x200, Line Creator will create all lines on the date specified
Gui Font
Gui Tab, 2
Gui Font, s10 c0xFFFFFF
Gui Add, Text, x208 y264 w435 h23 +0x200, 1. Ensure that E21 is running with the window open
Gui Font
Gui Font, s10 c0xFFFFFF
Gui Add, Text, x208 y216 w434 h29 +0x200, Auto Days input default schedule for given day
Gui Font
Gui Font, s10 c0xFFFFFF
Gui Add, Text, x208 y296 w435 h23 +0x200, 2. Navigate to Final Production Schedule
Gui Font
Gui Font, s10 c0xFFFFFF
Gui Add, Text, x208 y328 w474 h23 +0x200, 3. Search for desired date to input default (Day Must Be Blank)
Gui Font
Gui Font, s10 c0xFFFFFF
Gui Add, Text, x208 y360 w435 h23 +0x200, 4. Ensure that you are on Line A
Gui Font
Gui Font, s10 c0xFFFFFF
Gui Add, Text, x208 y392 w435 h23 +0x200, 5. Click desired Auto Day Button
Gui Font
Gui Font, s10 c0xFFFFFF
Gui Add, Text, x208 y424 w435 h23 +0x200, 6. Press F2 to execute automation
Gui Font
Gui Tab, 3
Gui Font, s10 c0xFFFFFF
Gui Add, Text, x208 y216 w434 h29 +0x200, Warning!! Batcher is ALPHA!!
Gui Font
Gui Font, s10 c0xFFFFFF
Gui Add, Text, x208 y248 w437 h29 +0x200, Quantities must be greater than 1000
Gui Font
Gui Font, s10 c0xFFFFFF
Gui Add, Text, x208 y280 w434 h29 +0x200, and not evenly divisible by 4000
Gui Font
Gui Font, s10 c0xFFFFFF
Gui Add, Text, x208 y312 w472 h29 +0x200, EX: If QTY = 20000 add 1000 then delete 1000 on final sch
Gui Font
Gui Tab

Gui Show, w715 h505, Arcadia Schedule Automator
Return

Line: 
    Run "%A_ScriptDir%\specs\0 Line Creator.exe"
    Return

Mon: 
    Run "%A_ScriptDir%\specs\1 Monday Default.exe"
    MsgBox 0x30, Warning!, SCRIPT IS ACTIVE! `n`nIF F2 IS PRESSED SCRIPT WILL RUN.`n`nENSURE FINAL SCEDULE LINE A IS SELECTED WITH CORRECT DATE
    Return

Tues: 
    Run "%A_ScriptDir%\specs\2 Tuesday Default.exe"
    MsgBox 0x30, Warning!, SCRIPT IS ACTIVE! `n`nIF F2 IS PRESSED SCRIPT WILL RUN.`n`nENSURE FINAL SCEDULE LINE A IS SELECTED WITH CORRECT DATE
    Return

Wed: 
    Run "%A_ScriptDir%\specs\3 Wednesday Default.exe"
    MsgBox 0x30, Warning!, SCRIPT IS ACTIVE! `n`nIF F2 IS PRESSED SCRIPT WILL RUN.`n`nENSURE FINAL SCEDULE LINE A IS SELECTED WITH CORRECT DATE
    Return

Thur: 
    Run "%A_ScriptDir%\specs\4 Thursday Default.exe"
    MsgBox 0x30, Warning!, SCRIPT IS ACTIVE! `n`nIF F2 IS PRESSED SCRIPT WILL RUN.`n`nENSURE FINAL SCEDULE LINE A IS SELECTED WITH CORRECT DATE
    Return

Fri: 
    Run "%A_ScriptDir%\specs\5 Friday Default.exe"
    MsgBox 0x30, Warning!, SCRIPT IS ACTIVE! `n`nIF F2 IS PRESSED SCRIPT WILL RUN.`n`nENSURE FINAL SCEDULE LINE A IS SELECTED WITH CORRECT DATE
    Return

Batcher: 
    Run "%A_ScriptDir%\specs\Batcher.exe"
    Return

GuiEscape:
GuiClose:
    ExitApp
